# Generated by Django 4.0.5 on 2022-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchert',
            name='credit',
            field=models.IntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vouchert',
            name='debit',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
