# Generated by Django 4.0.5 on 2022-08-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_groupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='grunder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('und', models.CharField(max_length=255)),
            ],
        ),
    ]
