# Generated by Django 4.0.5 on 2022-09-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_vouchert_credit_alter_vouchert_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchert',
            name='ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreation'),
        ),
    ]
