# Generated by Django 4.0.5 on 2022-09-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_vouchert_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchert',
            name='credit',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vouchert',
            name='debit',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
