# Generated by Django 4.0.5 on 2022-08-18 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_grunder'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holders_name', models.CharField(max_length=255)),
                ('ac_no', models.IntegerField()),
                ('ifsc', models.IntegerField()),
                ('swiftcode', models.IntegerField()),
                ('bankname', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('checkbook', models.CharField(max_length=255)),
                ('checkprinting', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailname', models.CharField(max_length=255)),
                ('mailaddress', models.CharField(max_length=255)),
                ('mailcontry', models.CharField(max_length=255)),
                ('mailstate', models.CharField(max_length=255)),
                ('mailpin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.IntegerField()),
                ('regtype', models.CharField(max_length=255)),
                ('gst', models.IntegerField()),
                ('gstdetails', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledgername', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('under', models.CharField(max_length=255)),
                ('prbankdetals', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.bankdetail')),
                ('ledgermail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.mail')),
                ('ledgertax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tax')),
            ],
        ),
    ]
