# Generated by Django 4.0.5 on 2022-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_bankdetail_mail_tax_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='ac_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bankname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='checkbook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='checkprinting',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='holders_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='swiftcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='alias',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailaddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailcontry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailpin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailstate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='gst',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='gstdetails',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='pan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='regtype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
