# Generated by Django 4.0.5 on 2022-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_bankdetail_ac_no_alter_bankdetail_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='ac_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.IntegerField(default=False),
        ),
    ]
