# Generated by Django 4.0.5 on 2022-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_bankdetail_ac_no_alter_bankdetail_ifsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.IntegerField(),
        ),
    ]
