# Generated by Django 4.0.5 on 2022-09-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_vouchert_credit_alter_vouchert_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchert',
            name='under',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
