# Generated by Django 4.0.5 on 2022-09-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_vouchert_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='inincvouchert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdate', models.DateField()),
                ('particular', models.CharField(max_length=255)),
                ('under', models.CharField(max_length=255, null=True)),
                ('account', models.CharField(max_length=255)),
                ('vouchertype', models.CharField(max_length=255)),
                ('voucherno', models.IntegerField()),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreation')),
            ],
        ),
    ]
