# Generated by Django 4.0.5 on 2022-09-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_inincvouchert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='account',
            new_name='iaccount',
        ),
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='credit',
            new_name='icredit',
        ),
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='debit',
            new_name='idebit',
        ),
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='ledger',
            new_name='iledger',
        ),
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='particular',
            new_name='iparticular',
        ),
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='under',
            new_name='iunder',
        ),
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='vdate',
            new_name='ivdate',
        ),
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='voucherno',
            new_name='ivoucherno',
        ),
        migrations.RenameField(
            model_name='inincvouchert',
            old_name='vouchertype',
            new_name='ivouchertype',
        ),
    ]
