# Generated by Django 4.0.5 on 2022-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_bankdetail_ifsc_alter_bankdetail_swiftcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='ledgername',
        ),
        migrations.AddField(
            model_name='ledger',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
