# Generated by Django 4.0.5 on 2022-08-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_ledger_ledgername_ledger_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='name',
            new_name='lname',
        ),
    ]
