# Generated by Django 4.0.5 on 2022-08-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_name_ledger_lname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ledger',
            new_name='ledgercreation',
        ),
    ]
