# Generated by Django 4.0.5 on 2022-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_ininxvouchert'),
    ]

    operations = [
        migrations.AddField(
            model_name='inincvouchert',
            name='iopeningbal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ininxvouchert',
            name='iopeningbal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vouchert',
            name='openingbal',
            field=models.IntegerField(null=True),
        ),
    ]
