# Generated by Django 4.0.5 on 2022-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_ledger_ledgercreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='ac_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='swiftcode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailpin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tax',
            name='gst',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tax',
            name='pan',
            field=models.BooleanField(default=False),
        ),
    ]
