# Generated by Django 4.0.5 on 2022-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_bankdetail_ac_no_alter_bankdetail_ifsc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgercreation',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='ledgercreation',
            name='ledgermail',
        ),
        migrations.RemoveField(
            model_name='ledgercreation',
            name='ledgertax',
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='ac_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='bankname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='checkbook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='checkprinting',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='gst',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='gstdetails',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='holders_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='ifsc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='mailaddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='mailcontry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='mailname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='mailpin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='mailstate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='pan',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='regtype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='swiftcode',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='bankdetail',
        ),
        migrations.DeleteModel(
            name='mail',
        ),
        migrations.DeleteModel(
            name='tax',
        ),
    ]
