# Generated by Django 4.0.5 on 2022-08-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_ledgercreation_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
                ('debit', models.IntegerField()),
            ],
        ),
    ]
