# Generated by Django 4.0.5 on 2022-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_cred'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='namegroup',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
