# Generated by Django 4.0.5 on 2022-08-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_led'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='led',
            name='rf',
        ),
    ]
