# Generated by Django 4.0.5 on 2022-08-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_led_rf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='checkbook',
            new_name='Echeque_p',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='checkprinting',
            new_name='SA_cheque_bk',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='holders_name',
            new_name='ac_holder_nm',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='ac_no',
            new_name='acc_no',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='prbankdetals',
            new_name='bank_details',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='bankname',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='mailcontry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='gst',
            new_name='gst_uin',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='ifsc',
            new_name='ifsc_code',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='mailname',
            new_name='mname',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='lname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='pan',
            new_name='pan_no',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='mailpin',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='regtype',
            new_name='registration_type',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='gstdetails',
            new_name='set_alter_gstdetails',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='mailstate',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='ledgercreation',
            old_name='swiftcode',
            new_name='swift_code',
        ),
        migrations.RemoveField(
            model_name='ledgercreation',
            name='mailaddress',
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='Alter_GST_Details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='Appropriate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='GST_Applicable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='Types_of_supply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='balance_billbybill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='credit_period',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='creditdays_voucher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='percentage_of_calcution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='rond_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='rond_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='rounding_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='rounding_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='set_odl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='tax_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='type_duty_tax',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='type_of_ledger',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
