# Generated by Django 4.0.5 on 2022-08-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_checkbook_ledgercreation_echeque_p_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='used_for_calculation',
            new_name='calculation',
        ),
        migrations.RenameField(
            model_name='groupmodel',
            old_name='nett_debit_credit_bal_reporting',
            new_name='debit_credit',
        ),
        migrations.RenameField(
            model_name='groupmodel',
            old_name='alias',
            new_name='group_alias',
        ),
        migrations.RenameField(
            model_name='groupmodel',
            old_name='name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='groupmodel',
            old_name='under',
            new_name='group_under',
        ),
        migrations.RenameField(
            model_name='groupmodel',
            old_name='method_to_allocate_usd_purchase',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='groupmodel',
            old_name='gp_behaves_like_sub_ledger',
            new_name='sub_ledger',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='gross_profit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='nature',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
