# Generated by Django 4.0.5 on 2022-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_rename_used_for_calculation_groupmodel_calculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgercreation',
            name='statutory_details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
