# Generated by Django 4.0.5 on 2022-08-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_ledgercreation_statutory_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='namegroup',
        ),
    ]
