# Generated by Django 4.0.5 on 2022-08-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_groupmodel_namegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255, null=True)),
                ('uname', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='bbnk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.bank'),
        ),
    ]
