# Generated by Django 4.0.5 on 2022-08-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_bank_ledgercreation_bbnk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgercreation',
            name='bbnk',
        ),
        migrations.DeleteModel(
            name='bank',
        ),
    ]
