# Generated by Django 4.0.5 on 2022-08-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_ledgercreation_bbnk_delete_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_Echeque_p',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_SA_cheque_bk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_ac_holder_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_acc_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_ifsc_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_set_odl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_swift_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_Echeque_p',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_SA_cheque_bk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_ac_holder_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_acc_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_ifsc_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_set_odl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_swift_code',
            field=models.IntegerField(null=True),
        ),
    ]
