# Generated by Django 4.0.5 on 2022-08-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_ledgercreation_occ_echeque_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgercreation',
            name='set_odl',
        ),
    ]
